### ISSUE TITLE
Ask Rotate Text

### ISSUE THREAD

**Issue by fhederico** [stedekay/SpraedPDFGeneratorBundle#20]
Hello, excuse my English is very bad.
I wanted to ask if it supports rotated text, and so far I have tried these options without success

1)
```
.rotate {
  -webkit-transform: rotate(-90deg);
  -moz-transform: rotate(-90deg);
  -ms-transform: rotate(-90deg);
  -o-transform: rotate(-90deg);
  transform: rotate(-90deg);

  -webkit-transform-origin: 50% 50%;
  -moz-transform-origin: 50% 50%;
  -ms-transform-origin: 50% 50%;
  -o-transform-origin: 50% 50%;
  transform-origin: 50% 50%;

  filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
}
```

2)
```
<div style="height: 100px; width: 100px; transform: translate(80px, 80px) scale(1.5, 1.5) rotate(45deg);">
		 PRUEBA DE TEXTO
</div>
```

Thank you

**Comment by fracich** [comment]
I'm having the same issue, someone can solve it?

**Comment by stedekay** [comment]
I'll have to apologize that I didn't answer anyone of you in that long time. I'm working on it that this won't happen again in future ;)

Unfortunately it is not possible to use rotate because this is a CSS3 feature. Flying saucer only works with CSS2.1.
