### ISSUE TITLE
some of Turkish character did not appear

### ISSUE THREAD

**Issue by highelf** [stedekay/SpraedPDFGeneratorBundle#21]
I try to write Turkish character with UTF-8 ecnocde but some of them such as `ı İ ğ ş`  did not appear in the pdf file .

**Comment by stedekay** [comment]
Sorry that I didn't answer you in an adequate time. I'm workin on it that this won't happen anymore.
If your problem still exists and you are still using this bundle can you provide me your template that you are trying to generate?

**Comment by Trung1994** [comment]
Hey stedekay. 

I've got that issue as well. It seems like that it's unable to render the non-latin letters, for example the greek letter for alpha, "α", or the greek letter for delta, "δ". 

I am rest assured that it might have something to do with the java file, but I'm of course unable to view the source. 

I would be glad if you could solve this issue. :-) 

Many thanks!

**Comment by stedekay** [comment]
You can have a look at the Java code at https://github.com/stedekay/SpraedPDFGenerator.
Otherwise I do need a code example.

**Comment by Trung1994** [comment]
Code example is here. 

public function getPdf() { 
        $html = "<strong> &alpha; </strong>"; // The &alpha; is for the greek alpha letter (non-latin)
        $pdf = $pdfGenerator->generatePDF($html); 
       

        // Output the PDF file. 
        return new Response($pdf, 200, array(
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'inline; filename="pdffile.pdf"'
                )
        );

**Comment by ux226** [comment]
Any news on this?

**Comment by stedekay** [comment]
Sorry that I never answered anymore to this issue.
This library was maintained poorly by me the last couple years due to spending less time for Open Source, more for my family (and this priority will also exist in the future).

If this issue still exists, please open a new issue and I will try my best to help out.
