### ISSUE TITLE
page-break does not work

### ISSUE THREAD

**Issue by gautierderuette** [stedekay/SpraedPDFGeneratorBundle#36]
It seems that 

`page-break-after: always;`

is not supported by the pdfGenerator

**Comment by stedekay** [comment]
We use it a lot and there are no issues known to me. Can you provide an example?

**Comment by gautierderuette** [comment]
Ho ! When the div is not empty it works ! 

`<div style="page-break-before: always;">
    Test
</div>`

**Comment by stedekay** [comment]
This seems to be the default behaviour: https://www.w3schools.com/cssref/pr_print_pageba.asp

> Note: You cannot use this property on an empty div or on absolutely positioned elements.

**Comment by gautierderuette** [comment]
Ok my bad. Thank you
