### ISSUE TITLE
Symfony4, unable to use service in controller

### ISSUE THREAD

**Issue by balvirsingh** [stedekay/SpraedPDFGeneratorBundle#39]
Hi,

I am using symfony 4. When I call the service in controller - 
`$this->get('spraed.pdf.generator');`

It gives an error  - 
> Service "spraed.pdf.generator" not found: even though it exists in the app's container, the container inside "App\Controller\TrainingController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "session" and "twig" services. Try using dependency injection instead.

Please suggest me, how can I use it in symfony 4 .

Thanks.

**Comment by dhodo** [comment]
Try to run **bin/console debug:container spraed.pdf.generator** in console to check if your service is correctly registered.

You can check in your config/bundles.php whether you've got this line:

**Spraed\PDFGeneratorBundle\SpraedPDFGeneratorBundle::class => ['all' => true],**

I hope it helps
